version: "3.8"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: verd_dev
      POSTGRES_USER: verd_dev
      POSTGRES_DB: verd_dev

  web-app:
    build:
      context: .
      dockerfile: ./ops/Dockerfile.local
    depends_on:
      db:
        condition: service_started
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: npm run dev

