import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Hotjar from "@hotjar/browser";

const inter = Inter({ subsets: ["latin"] });

const isProdNodeEnv = process.env.NODE_ENV === "production";
const gtmMeasurementId = process.env.NEXT_PUBLIC_GTM_MEASUREMENT_ID;
const hotjarSiteId = process.env.NEXT_PUBLIC_HOTJAR_SITE_ID
  ? parseInt(process.env.NEXT_PUBLIC_HOTJAR_SITE_ID)
  : undefined;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
    googleBot: {
      index: false,
      follow: false,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (isProdNodeEnv && hotjarSiteId) {
    Hotjar.init(hotjarSiteId, 6);
  }

  return (
    <html lang="en">
      {isProdNodeEnv && gtmMeasurementId && (
        <Script id="gtm">
          {`
            <!-- Google tag (gtag.js) -->
            <script async src="https://www.googletagmanager.com/gtag/js?id=${gtmMeasurementId}"></script>
            <script>
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', '${gtmMeasurementId}');
            </script>
          `}
        </Script>
      )}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
